name: Run tests

on:
  workflow_call: {}

jobs:
  pack_shared_lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: Download deps
        working-directory: shared
        run: |
          echo *** INSTALLING deps ***
          npm ci

          echo *** BUILDING PACKAGE ***
          npm run build

          echo *** NPM PACK ***
          npm pack
