name: Deploy to Firebase Functions and Hosting on release

on:
  release:
    types:
      - published
# env:
# CI: false

jobs:
  pack_shared_lib:
    uses: ./.github/workflows/bundle-shared-lib.yml

  build_and_deploy_functions_on_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Download deps
        working-directory: functions
        run: npm install

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GET_INTO_FORM }}' > $HOME/gcloud.json

      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions:api_prd
        env:
          NODE_ENV: production

  build_and_deploy_hosting_on_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: hosting
        run: npm ci

      - name: Build
        working-directory: hosting
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GET_INTO_FORM }}"
          channelId: live
          projectId: impresaner-forms
          target: impresaner-forms
