name: Deploy to Firebase Functions and Hosting on merge

on:
  push:
    branches:
      - main
# env:
# CI: false

jobs:
  build_and_deploy_functions_on_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Download deps
        working-directory: shared
        run: |
          echo *** INSTALLING deps ***
          npm ci

          echo *** BUILDING PACKAGE ***
          npm run build

          echo *** NPM PACK ***
          npm pack

      - name: Download deps
        working-directory: functions
        run: npm install

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GET_INTO_FORM }}' > $HOME/gcloud.json

      - name: Deploy Cloud Functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json 

          cd functions

          npm ci
          npm run lint

          mv ../shared/shared-1.0.0.tgz shared-1.0.0.tgz

          npm install shared-1.0.0.tgz
          npm run build

          cd ..

          echo NODE_ENV=staging > functions/.env
          mkdir -p functions/lib/.env
          NODE_ENV=staging npx firebase-tools deploy --only functions:api_stg

  build_and_deploy_hosting_on_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download deps
        working-directory: shared
        run: |
          echo *** INSTALLING deps ***
          npm ci

          echo *** BUILDING PACKAGE ***
          npm run build

          echo *** NPM PACK ***
          npm pack

      - name: Install dependencies
        working-directory: hosting
        run: npm ci

      - name: Build
        working-directory: hosting
        run: npm run build:stg

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GET_INTO_FORM }}"
          projectId: impresaner-forms
          channelId: live
          target: impresaner-forms-stg
